### ISSUE TITLE
Import Error: no module named 'smbus'

### ISSUE THREAD

**Issue by paul-mc** [pimoroni/ltr559-python#16]
I'm attempting to run the proximity-and-light.py example on a Pico W but i'm getting the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 6, in <module>
  File "/lib/ltr559/__init__.py", line 212, in __init__
  File "/lib/i2cdevice/__init__.py", line 165, in __init__
ImportError: no module named 'smbus'
```

I'm running the latest release of ltr559-python (0.1.1) installed via Manage Packages in Thonny

I'm running [pimoroni-picow-v1.19.16-micropython.uf2](https://github.com/pimoroni/pimoroni-pico/releases/download/v1.19.16/pimoroni-picow-v1.19.16-micropython.uf2) on a Pico W board

I've tried installing smbus via the Thonny package manager, but that hasn't resolved the issue

any help appreciated

**Comment by helgibbons** [comment]
This library and its examples are for use with full-fat Python on Raspberry Pi SBC. For a Pico try this MicroPython example:

https://github.com/pimoroni/pimoroni-pico/blob/main/micropython/examples/breakout_ltr559/demo.py

(You'll also need to be running one of our custom MicroPython builds which has the breakout drivers built in, but it sounds like you've already found that!)

**Comment by paul-mc** [comment]
thanks for your help @helgibbons - that makes perfect sense - I'll close this issue :)
